version: '3.8'
services:
  postgres:
    container_name: "postgres"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./doc/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    # Configuration for building the docker image for the service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
volumes:
  db:
    driver: local